### ISSUE TITLE
unknown function: spectacular#add_test_runner

### ISSUE THREAD

**Issue by cartoloupe** [davidpdrsn/vim-spectacular#11]
In `~/.vimrc`, the vim-spectacular plugin is called like this:
```vim
Plugin 'davidpdrsn/vim-spectacular'
```

but when I start vim, I get the following error:

```bash
line  513:
E117: Unknown function: spectacular#add_test_runner
```

Is there something I can do to "re-install" the plugin?

**Comment by davidpdrsn** [comment]
You can reinstall the plugin like so

1. Remove the plugin from you vimrc
2. Source vimrc or restart vim
3. Run :PluginClean
4. Install again as usual

Let me know if you still have issues :smile:

-- 
David Pedersen

On 12 Feb 2015 at 15:09:47, cartoloupe (notifications@github.com) wrote:

In ~/.vimrc, the vim-spectacular plugin is called like this:

Plugin 'davidpdrsn/vim-spectacular'
but when I start vim, I get the following error:

line  513:
E117: Unknown function: spectacular#add_test_runner
Is there something I can do to "re-install" the plugin?

**Comment by cartoloupe** [comment]
Thanks @davidpdrsn -- I did the following and now can kick off tests with `<leader>t`:

1. commented out plugin in vimrc
2. restarted vim
3. ran :PluginClean
4. ran :PluginInstall

I have run into another problem but will describe it another issue.
