### ISSUE TITLE
gemfile syntax error compile error

### ISSUE THREAD

**Issue by cartoloupe** [davidpdrsn/vim-spectacular#12]
When I run a test with `<leader>t`, it seems that an older version of ruby is used to run the tests, because I get an error like this:

```bash
Gemfile syntax error compile error
on line 29: syntax error, unexpected ':', expecting $end
gem 'sdoc', '~> 0.4.0',          group: :doc
                                       ^

shell returned 4

Press ENTER or type command to continue
```

these are the test runners I am using in vimrc:
```vim
call spectacular#add_test_runner('ruby', 'bundle exec rspec {spec}', '_spec', function("IncludesRspecGem"))
call spectacular#add_test_runner('ruby', 'rspec {spec}', '_spec')
```

My system ruby seems up to date:
```bash
ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

And I am able to `bundle exec rspec <target spec file>` via the command line... what can I troubleshoot next?

**Comment by davidpdrsn** [comment]
There might be a problem with you `IncludesRspecGem` function. Maybe it doesn't work the way you expect.

You can see exactly which test command is being run by putting `let g:spectacular_debugging_mode = 0` in your vimrc and running `:messages` after running some tests. Then you should then be able to see if things are working as expected.

**Comment by davidpdrsn** [comment]
Or maybe your vim isn't configured with the right ruby version. I'm using [this plugin](https://github.com/tpope/vim-rbenv) together with [rbenv](https://github.com/sstephenson/rbenv).

**Comment by davidpdrsn** [comment]
I'll assume this has been fixed, feel free to reopen it if not.
